name: google_ml_kit_example
description: Demonstrates how to use the google_ml_kit plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  path_provider: ^2.1.0

  google_mlkit_commons:
#    path: ../google_mlkit_commons
  google_mlkit_pose_detection:
    path: ../google_mlkit_pose_detection
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/
